name: build Re:VIEW PDF and EPUB

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: generate PDF and EPUB
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build PDF
      uses: takahashim/review-pdf-generator-action@master
    - name: upload as Artifacts
      uses: takahashim/review-pdf-generator-action/upload-artifact@master
    - name: build EPUB
      uses: Nyoho/review-epub-generator-action@master
    - name: upload as Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: epub
        path: build/output.epub
