name: build Re:VIEW EPUB

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: generate EPUB
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build EPUB
      uses: Nyoho/review-epub-generator-action@master
    - name: upload as Artifacts
      uses: Nyoho/review-epub-generator-action/upload-artifact@master
